### ISSUE TITLE
Conformer search not working in Windows version

### ISSUE THREAD

**Issue by kjellarne-tech** [OpenChemistry/avogadrolibs#2160]
**Avogadro version: (please complete the following information from the About box): 1.100.0-639-g24c81f59
 - Avogadrolibs: 1.100.0-639-g24c81f59
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Win11.64bit Enterprise
 - Version 23H2
 - Compiler (if you built from source) - (nightly build install)

**Describe the bug**
Unable to perform the Conformère search. The dialog show zero number of atoms, for any molecule. This feature has not worked in any previous version of Avogadro2.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by ghutchis** [comment]
Can you please try a nightly build from https://two.avogadro.cc/install/ - I'm pretty sure this is already fixed in recent builds.

**Comment by kjellarne-tech** [comment]
Thanks for prompt answer. I DID use the latest nightly build: 1.100.0-639-g24c81f59. The same on another computer running Windows 10. Hopefully it will be solved. 

(As for #2159: The issue of ambivalent forcefield is still present, as it always was for Avogadro 1. I'll have a look at the Discussion.)

**Comment by kjellarne-tech** [comment]
Another thought - how about Python? I read a lot about Python scripts in the discussions, Python is some stuff that needs to be installed?

**Comment by ghutchis** [comment]
Python scripts are used for many of the plugins, including input generators for a range of programs (e.g., ORCA). But they're not required for core functions, e.g. this particular issue.

**Comment by ghutchis** [comment]
Can you please try the 1.101 release or a nightly build? I'm pretty confident this is fixed in the current builds and would like to close this. Thanks!

**Comment by ghutchis** [comment]
I'm going to close this - if you're still experiencing problems with 1.102.x, please submit a new bug. It seems to work for me as well as my students.
