### ISSUE TITLE
Avogadro Won't Open if Python isn't Installed?

### ISSUE THREAD

**Issue by petroffc** [OpenChemistry/avogadrolibs#2330]
**Avogadro version::**
 - Avogadrolibs: 1.102.0 Windows EXE

**Desktop version:**
 - OS: Windows
 - Version Windows 10 Pro

**Describe the bug:**
When Avogadro is opened on a system without Python installed, a dialog appears asking if the user wants to install Python. After clicking No, nothing appears to happen; the program never opens. When shutting down the system, a pixi.exe error message briefly appears.

**To reproduce:**
1. Install the Avogadro EXE on a system without Python installed.
2. Open Avogadro.
3. A dialog box appears (Install Python):
```
Python is used for many Avogadro features. Do you want to download Python?
```
4. Click No.
5. The dialog closes and the main application window never opens.
6. Shutdown the system.
7. During the shutdown sequence, an error dialog briefly appears (pixi.exe - Application Error)
```
The application was unable to start correctly (0xc0000142). Click OK to close the application.
```

**Expected behavior:**
Avogadro opens without Python-dependent features available.

**Comment by ghutchis** [comment]
Thanks. That's incredibly weird. For one, the path that calls `pixi` will never run unless you click `Yes` in the dialog. For another, I tested both paths pretty carefully. If you click "No" the app should launch, but you'll be asked again. (Too many Windows users wonder why they don't have an ORCA input generator -- because a lot of features use Python.)

- Did you install from our installer or the MS Store?
- Does this happen again on re-launch?

**Comment by petroffc** [comment]
I used the [.exe installer](https://github.com/OpenChemistry/avogadrolibs/releases/latest/download/Avogadro2-1.102.0-win64.exe) linked from the Avogadro website.

The same thing happens at relaunch; no matter how many times I try, I can't get the main Avogadro window to open.

Curiously, I don't have the `pixi.exe` error on shutdown anymore. I tried to kill `pixi.exe` with Task Manager and it wouldn't let me (nothing would happen when I clicked the End Task button and I got some error message if I clicked End Task in the right-click menu). Eventually, it did close. Since then, it doesn't appear in Task Manager when I try to run Avogadro, but Avogadro still doesn't open.

While unlikely to be relevant, this Windows install, as you may have surmised, is on a VM.

**Comment by ghutchis** [comment]
Thanks.

I think I know what's happening. It's leaving that part of the code - you didn't install `python`. But then it tries to load the various scripts and it doesn't have a proper `python` install. But it does have `pixi` .. which is hanging.

I've thought through this logic a bit and I think #2337 should fix it (i.e., because you didn't install `python` there shouldn't be a `.pixi` directory and it should give up trying to run the scripts.

It should build in about an hour and I'll paste the `exe` over here.

**Comment by ghutchis** [comment]
Okay, you should be able to use:
https://github.com/OpenChemistry/avogadrolibs/actions/runs/18808878314/artifacts/4372259181

Or the next nightly build

**Comment by petroffc** [comment]
@ghutchis I tried the Windows build that incorporated #2337, and it seems to have no effect.

Installing Python stopped the popup from opening, but Avogadro still doesn't load.

Upon further digging, I've discovered that the `pixi.exe` and Avogadro not opening issues are unrelated.

**Avogadro Not Opening:**
I looked at the Avogadro log file, and the last entry is always:
```
Warning: QOpenGLWidget: Failed to create wrapper texture (:0, )
```
So, Avogadro not opening is an OpenGL issue and is related to the VM after all.

With this VM configuration (VirtualBox with no 3D acceleration), `GLview Extensions Viewer` (which I found recommended by an ESRI support article about OpenGL issues) displays the following OpenGL info:
```
Core GL Version: 1.1
Shading Language Version: [blank]
Compatibility GL ES Version: N/A
```
It crashes when I try initializing its OpenGL rendering tests.

If I enable 3D hardware acceleration in VirtualBox, it displays the following OpenGL info:
```
Core GL Version: 4.1 (Compatibility Profile) Mesa messa-21
Shading Language Version: 4.10
Compatibility GL ES Version: 3.0
```
In this case, its OpenGL rendering tests run and *Avogadro opens without issue*.

**`pixi.exe` Issues:**
On a different VM image, I tried both the v1.102.0 and the #2337 builds. For both builds, when 3D acceleration is enabled, `pixi.exe` opens when I click no on the Python prompt and runs until the main Avogadro window opens (15--30 s). When 3D acceleration is disabled (and Avogadro crashes), `pixi.exe` still runs for 15--30 s before closing (I had been trying to open Avogadro several times and then immediately shutting down the VM upon giving up, hence the error at shutdown); Avogadro crashes after 5--10 s. It's still unclear how ending the `pixi.exe` task on my other VM image has seemingly permanently stopped `pixi.exe` from running there.

**Comment by ghutchis** [comment]
I'd be curious to see the `avogadro2.log` if `pixi` is running even if you said no to the install with the #2337 build.

But I'm glad you got it going. Certainly with only OpenGL 1.1 support, nothing would have worked.

**Comment by petroffc** [comment]
With the #2337 build, the only difference (besides the Open Babel build date) in the log file is that the following is missing from the log before each warning about not being able to load the 11 input generator scripts and the one format script:
```
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
```

v1.102.0:
```
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/dalton.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/gamessuk.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/gaussian.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/molpro.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/mopac.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/nwchem.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/orca.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/psi4.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/pyscf.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/qchem.py" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/terachem.py" (:0, )
Debug:  loading extension plugin:  "Quantum input" (:0, )
Debug:  loading extension plugin:  "Script Charge Models" (:0, )
Warning: Python interpreter "C:/hostedtoolcache/windows/Python/3.12.10/x64/python3.exe" does not exist trying "python" in your path. Please set a path to the python interpreter. (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/formatScripts/zyx.py" (:0, )
```

#2337:
```
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/dalton.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/gamessuk.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/gaussian.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/molpro.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/mopac.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/nwchem.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/orca.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/psi4.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/pyscf.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/qchem.py" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/inputGenerators/terachem.py" (:0, )
Debug:  loading extension plugin:  "Quantum input" (:0, )
Debug:  loading extension plugin:  "Script Charge Models" (:0, )
Debug: Using manifest in "C:/Users/user/AppData/Local/OpenChemistry/Avogadro" (:0, )
Warning: "Cannot load script C:/Program Files/Avogadro2/lib/avogadro2/scripts/formatScripts/zyx.py" (:0, )
```
