### ISSUE TITLE
Avogadro crashes when uploading a PDB file

### ISSUE THREAD

**Issue by a-cheminfo** [OpenChemistry/avogadrolibs#2456]
**Avogadro version:**
 - Avogadrolibs: 1.120.1
 - Qt: 6.10.0

**Desktop version: **
 - OS: Windows 11 Pro

**Describe the bug**
Crashes immediately when attempting to upload a PDB format file. When clicked on open, program shows the "Reading File" pop-up window which disappears instantly and the program crashes.

**To Reproduce**
1. Open Avogadro 2
2. Load peptide PDB
3. Starts loading
4. Crash occurs

**Expected behavior**
The program should upload a PDB file and run a basic geometry optimization on it.

**Comment by a-cheminfo** [comment]
The file I tried uploading:

[1.pdb](https://github.com/user-attachments/files/23829582/1.pdb)

**Comment by ghutchis** [comment]
Thanks. This absolutely works for me in the latest build. Can you try installing from https://github.com/openchemistry/avogadrolibs/releases/continuous

It might be a Windows specific thing, but there are a bunch of bugs we've fixed since 1.102.1

<img width="555" height="393" alt="Image" src="https://github.com/user-attachments/assets/9e648644-e9ec-442d-b8b7-0af45daa535f" />

**Comment by a-cheminfo** [comment]
I deleted Avogadro2, reinstalled it from the link you sent (downloaded [Avogadro2-continuous-win64.exe](https://github.com/OpenChemistry/avogadrolibs/releases/download/continuous/Avogadro2-continuous-win64.exe)) , tried uploading and the issue still persists for some reason.

**Comment by ghutchis** [comment]
Okay, thanks - I'll see if I can sort out the issue this weekend.

**Comment by ghutchis** [comment]
Just to check - are you okay if I add this to the test set so I can further investigate the crash on Windows?

**Comment by a-cheminfo** [comment]
Sure, no problem.

**Comment by ghutchis** [comment]
I still have not been able to reproduce this, even with the new tests on Windows.

Can you please try with a new continuous build from https://github.com/openchemistry/avogadrolibs/releases/continuous and let me know if it's still an issue? I found a few minor things that were fixed in #2459

**Comment by ghutchis** [comment]
I'm closing this, since I can't reproduce it with 1.103. If you run into further problems, please open a new bug report. Thanks!
