### ISSUE TITLE
1.95.0 Black screen instead of a molecule

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#733]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.95.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: FreeBSD 13
 - Version: 1.95.0
 - Compiler clang-11

**Describe the bug**
```avogadro2``` starts with an entirely black molecule widget.
When *.pdb file is opened it only shows a box in white lines and nothing else.

This is a regression against 1.94.0 which showed *.pdb files fine.

```
$ avogadro2 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-yuri'
Locale:  "C"
Extension plugins dynamically found... 35
Checking for  "commands"  scripts in "/home/yuri/.local/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/local/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/local/bin/../lib/avogadro2/scripts/commands"
OBProcess::executeObabel: Running "obabel" "-L formats read"
OBProcess::executeObabel: Running "obabel" "-L formats write"
OBProcess::executeObabel: Running "obabel" "-L forcefields"
OBProcess::executeObabel: Running "obabel" "-L charges"
OBProcess::executeObabel: Running "obabel" "-V"
"obabel"  found:  ""
Checking for  "inputGenerators"  scripts in "/home/yuri/.local/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/local/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/local/bin/../lib/avogadro2/scripts/inputGenerators"
Checking for  "formatScripts"  scripts in "/home/yuri/.local/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/local/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/local/bin/../lib/avogadro2/scripts/formatScripts"
"Navigator" added
"Editor" added
"Selection" added
"Manipulator" added
"BondCentric" added
"MeasureTool" added
"PlayerTool" added
Process encountered an error, and did not execute correctly.
	Exit code: 0
	Exit status: QProcess::NormalExit
	Exit output: ""
Open Babel formats ready:  0
Process encountered an error, and did not execute correctly.
	Exit code: 0
	Exit status: QProcess::NormalExit
	Exit output: ""
Process encountered an error, and did not execute correctly.
	Exit code: 255
	Exit status: QProcess::NormalExit
	Exit output: ""
Process encountered an error, and did not execute correctly.
	Exit code: 0
	Exit status: QProcess::NormalExit
	Exit output: ""
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by yurivict** [comment]
https://user-images.githubusercontent.com/271906/129792858-618b071c-626b-4516-ad88-9e2bff5700ab.mp4

**Comment by ghutchis** [comment]
I'm not sure of the bug at the moment - but the workaround is to click the "Ball and Stick" or "Cartoon" or "Wireframe" display types.

**Comment by ghutchis** [comment]
(The bug would be that "Ball and Stick" should be the default on a new install.)

**Comment by yurivict** [comment]
Can you release a fix in a new release?

**Comment by ghutchis** [comment]
Sure, although did you have previous settings on that account? I'll test a bit later with cleared settings.

**Comment by yurivict** [comment]
> Sure, although did you have previous settings on that account?

Probably not.

Now this version creates settings files but doesn't initialize this value, so the problem is reproducible on reruns.

**Comment by ghutchis** [comment]
I can confirm that the default value is somehow getting ignored.

<img width="291" alt="Screen Shot 2021-08-18 at 11 08 05 AM" src="https://user-images.githubusercontent.com/41128/129923734-13c8c045-0713-4f90-836b-2badf4b901bc.png">

> Now this version creates settings files but doesn't initialize this value

Well, if you enable "Ball and Stick" or any other display type, it **will** be saved to the settings on re-run.

**Comment by ghutchis** [comment]
I'll take a closer look into the code later this afternoon.

**Comment by serk12** [comment]
I think I solved the problem with the black screen. 
Yuri is not only starting a fresh install, but also opening a file. So `ballandstick/enable` patch the 1º run but `MainWindow/plugin` has not changed, so when the file is opened it gets back to false. 
This should solve it, but we need the plugin name which is set up in the `CMakeList.txt`, any clean solution?
```
@@ -89,9 +89,11 @@ void PluginLayerManager::setEnabled(bool enable)
     if (m_name == BallAndStick::getName()) {
       enable = settings.value("ballandstick/enable", true).toBool();
       settings.setValue("ballandstick/enable", false);
+      settings.setValue("MainWindow/" + pluginName, false);
     } else if (m_name == Cartoons::getName()) {
       enable = settings.value("cartoon/enable", true).toBool();
       settings.setValue("cartoon/enable", false);
+      settings.setValue("MainWindow/" + pluginName, false);
     }

```

**Comment by ghutchis** [comment]
I still don't understand why the code is calling `setValue()` with `false` - shouldn't we be using `enable` so that on 2nd run, etc. it's correct?

As far as loading from a file, I think that needs to be solved in `avogadroapp` - perhaps a check if a file doesn't have any plugins enabled, to turn one on for the user .. but it's a small population that has files like this.

**Comment by serk12** [comment]
Yes, if we add a `isDefault` to `ScenePlugin` then all of this can be solved trivialy in `avogadroapp`.

**Comment by PeterKraus** [comment]
Has this been resolved? I'm seeing the same issue (ball & stick unchecked every time I open an xyz file, even if previously checked) on Linux with 1.95.1.

**Comment by yurivict** [comment]
I didn't see it resolved. I stopped updating the FreeBSD until this is resolved.

**Comment by serk12** [comment]
The pulls #807 and [avogadrolibs#235](https://github.com/OpenChemistry/avogadroapp/pull/235) should fix this. But they are posterior to 1.95.1.

**Comment by ghutchis** [comment]
We need a 1.96 release, but I'm marking this closed.

**Comment by ghutchis** [comment]
If problems re-occur with HEAD, please open a new bug report.

**Comment by yurivict** [comment]
> We need a 1.96 release, but I'm marking this closed.

Does this mean that the problem will be fixed in 1.96 ?

**Comment by ghutchis** [comment]
Yes. As far as I can tell, it's fixed in HEAD with #807 and [avogadroapp](https://github.com/OpenChemistry/avogadroapp/pull/235)
